# Embeds prebuilt stdlib archives (libqu-<arch>-linux.a) into a C++ header as
# byte arrays, one per target, so the compiler binary carries its own stdlib.
#
# Usage:
#   cmake -DQUANT_LIBQU_SPEC="x86_64-linux=/abs/libqu-x86_64-linux.a|aarch64-linux=/abs/libqu-aarch64-linux.a" \
#         -DOUTPUT_HEADER=/abs/header -P embed_lib.cmake

# Some CMake versions pass -D values through a shell that keeps the quotes.
string(REPLACE "\"" "" QUANT_LIBQU_SPEC "${QUANT_LIBQU_SPEC}")
string(REPLACE "\"" "" OUTPUT_HEADER "${OUTPUT_HEADER}")

if(QUANT_LIBQU_SPEC STREQUAL "")
    message(FATAL_ERROR "QUANT_LIBQU_SPEC is empty (expected <target>=<archive> pairs)")
endif()

string(REPLACE "|" ";" entries "${QUANT_LIBQU_SPEC}")

set(content "// Generated by scripts/embed_lib.cmake. Do not edit.\n")
string(APPEND content "#pragma once\n")
string(APPEND content "#include <vector>\n\n")
string(APPEND content "namespace quant::embedded_libqu {\n\n")
string(APPEND content "struct Archive {\n")
string(APPEND content "    const char* target;\n")
string(APPEND content "    const unsigned char* data;\n")
string(APPEND content "    unsigned long long size;\n")
string(APPEND content "};\n\n")

set(targets "")
set(symbols "")

foreach(entry IN LISTS entries)
    if(NOT entry MATCHES "^([^=]+)=(.*)$")
        message(FATAL_ERROR "Malformed QUANT_LIBQU_SPEC entry '${entry}' (expected <target>=<archive>)")
    endif()
    set(target "${CMAKE_MATCH_1}")
    set(archive "${CMAKE_MATCH_2}")

    if(NOT EXISTS "${archive}")
        message(FATAL_ERROR "Stdlib archive not found: ${archive}")
    endif()

    string(REGEX REPLACE "[^A-Za-z0-9]" "_" symbol "${target}")

    file(READ "${archive}" hex HEX)
    string(LENGTH "${hex}" hex_len)
    math(EXPR size "${hex_len} / 2")

    # 0xNN, per byte, wrapped every 16 bytes so no single line gets huge.
    string(REGEX REPLACE "(..)" "0x\\1," bytes "${hex}")
    string(REGEX REPLACE
        "(0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,)"
        "\\1\n    " bytes "${bytes}")

    string(APPEND content "// ${target} (${archive}, ${size} bytes)\n")
    string(APPEND content "inline const unsigned char kLibqu${symbol}[${size}] = {\n")
    string(APPEND content "    ${bytes}\n")
    string(APPEND content "};\n\n")

    list(APPEND targets "${target}")
    list(APPEND symbols "${symbol}")
    message(STATUS "Embedded stdlib archive ${archive} -> ${target} (${size} bytes)")
endforeach()

string(APPEND content "inline const std::vector<Archive>& archives() {\n")
string(APPEND content "    static const std::vector<Archive> kArchives = {\n")

list(LENGTH targets archive_count)
math(EXPR last_index "${archive_count} - 1")
foreach(index RANGE 0 ${last_index})
    list(GET targets ${index} target)
    list(GET symbols ${index} symbol)
    string(APPEND content "        {\"${target}\", kLibqu${symbol}, sizeof(kLibqu${symbol})},\n")
endforeach()

string(APPEND content "    };\n")
string(APPEND content "    return kArchives;\n")
string(APPEND content "}\n\n")
string(APPEND content "} // namespace quant::embedded_libqu\n")

get_filename_component(out_dir "${OUTPUT_HEADER}" DIRECTORY)
file(MAKE_DIRECTORY "${out_dir}")
file(WRITE "${OUTPUT_HEADER}" "${content}")